= Lab 1 - Getting Started with Spring Boot

. In your browser, visit http://start.spring.io.

. Fill out the *Project metadata* fields as follows:
+
Group:: `io.spring.pivotal`
Artifact:: `hello-spring-boot`
Name:: `hello-spring-boot`
Description:: `Hello Spring Boot`
Package Name:: `io.pivotal.spring.hello`
Type:: Maven Project
Packaging:: Jar
Java Version:: 1.7
Language:: Java
Spring Boot Version 1.2.3

. In the *Project dependencies* section, check the following:
+
* Web

. Click the *Generate Project* button. Your browser will download a zip file.
Unpack that zip file into a directory that you wish to work from.

. Import the project's `pom.xml` into your editor/IDE of choice.

. Add a `@RestController` annotation to the class `io.pivotal.spring.hello.HelloSpringBootApplication`.

. Add the following request handler to the class `io.pivotal.spring.hello.HelloSpringBootApplication`:
+
[source,java]
----
@RequestMapping("/")
public String hello() {
    return "Hello World!";
}
----

. Build the project with `mvn package`

. Run the project locally with `java -Dserver.port=8095 -jar target/hello-spring-boot-0.0.1-SNAPSHOT.jar`

. Browse to http://localhost:8095 to see your "Hello World!" message in all it's glory.

*Congratulations!*
You've just completed your first Spring Boot application.  Push it to your PCF development space to test it out in Cloud Foundry.